apiVersion: v1
kind: Service
metadata:
  name: {{ include "snake-game.fullname" . }}
spec:
  selector:
    app: {{ include "snake-game.name" . }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: {{ .Values.service.type }}
